### ISSUE TITLE
visualise bug when annotation obkect is empty

### ISSUE THREAD

**Issue by AnasAito** [AnasAito/SkillNER#35]
![image](https://user-images.githubusercontent.com/56308112/139923600-85310084-13ef-4b71-90bc-2324d448c990.png)

**Comment by Badr-MOUFAD** [comment]
Bug fixed!
It was handled in ``Phrase`` class to avoid mixing ``visualize`` and ``skill_extractor`` modules


![bug_visulize_skillNer](https://user-images.githubusercontent.com/65614794/140644500-cfa93ee4-8623-43bf-93f2-bda27de357cc.png)
